apiVersion: 1

datasources:
  - name: InfluxDB_v1
    type: influxdb
    access: proxy
    user: grafana
    url: https://${INFLUX_HOST}
    basicAuth: true
    basicAuthUser: user
    jsonData:
      dbName: ${INFLUX_BUCKET}
      httpMode: GET
    secureJsonData:
      password: ${INFLUX_TOKEN}
      basicAuthPassword: ${INFLUX_TOKEN}


