# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0


apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    readOnly: false
    editable: true
    isDefault: false
    jsonData:
      tracesToLogsV2:
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
        tags: []
        # Field with internal link pointing to a logs data source in Grafana.
        # datasourceUid value must match the datasourceUid value of the logs data source.
        datasourceUid: 'FlightSQL'
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: 'select * from logs'
      nodeGraph:
        enabled: true