# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0


apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    readOnly: false
    editable: true
    isDefault: false
    jsonData:
      tracesToLogsV2:
        spanStartTimeShift: '1m'
        spanEndTimeShift: '-1m'
        tags: []
        # Field with internal link pointing to a logs data source in Grafana.
        # datasourceUid value must match the datasourceUid value of the logs data source.
        datasourceUid: 'InfluxDB_v1'
        filterByTraceID: true
        filterBySpanID: false
        customQuery: false
        query: 'SELECT time, "event.name", "severity_text","severity_number" ,body, attributes FROM logs WHERE "trace_id" = ''${__span.spanId}'' AND time >= now() - 1h'
      nodeGraph:
        enabled: true