# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file
receivers:
  jaeger:
    protocols:
      thrift_compact:
      thrift_http:


exporters:
  influxdb:
    endpoint: https://${INFLUXDB_ADDR}
    bucket: ${INFLUXDB_BUCKET}
    token: ${INFLUXDB_TOKEN}
    metrics_schema: otel-v1
  
connectors:
  spanmetrics:
    aggregation_temporality: "AGGREGATION_TEMPORALITY_DELTA"
  servicegraph:

service:
  telemetry:
    logs:
      level: error
      encoding: json

  pipelines:
    traces:
      receivers: [otlp, jaeger]
      exporters: [influxdb, spanmetrics, servicegraph]

    metrics:
      receivers: [otlp, spanmetrics, servicegraph]
      exporters: [influxdb, prometheus]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [influxdb]