# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file

exporters:
  influxdb:
    endpoint: https://${INFLUXDB_ADDR}
    bucket: ${INFLUXDB_BUCKET}
    token: ${INFLUXDB_TOKEN}
    metrics_schema: otel-v1
  
connectors:
  spanmetrics:
    aggregation_temporality: "AGGREGATION_TEMPORALITY_DELTA"
  servicegraph:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [influxdb, spanmetrics, servicegraph]
    metrics:
      receivers: [spanmetrics, servicegraph]
      processors: [batch]
      exporters: [influxdb]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [influxdb]